name: namer_app
description: A new Flutter project.

publish_to: 'none' 
version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0-0
  provider: ^6.0.0
  flutter_riverpod: ^2.0.2
  shared_preferences: ^2.2.2
  uuid: ^4.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  